"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraUIProvider } from "@/provider/ChakraUIProvider";
import { RecoilRoot } from "recoil";
import { Box } from "@chakra-ui/react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const scrollbarStyle = {
  "&::-webkit-scrollbar": {
    width: "5px",
  },
  "&::-webkit-scrollbar-thumb": {
    background: "gray",
    borderRadius: "10px",
  },
  "&::-webkit-scrollbar-thumb:hover": {
    background: "gray.400",
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Box
        sx={scrollbarStyle}
        maxH={"100vh"}
        overflowY={"scroll"}
        minH={"100vh"}
        flex={1}
      >
        {/* <SideBar /> */}
        {/* <Divider orientation="vertical" /> */}
        <Box px={"50px"} pt={"150px"} flex={"1"} pb={"50px"} minH={"100vh"}>
          {/* <body className={inter.className}> */}
            <RecoilRoot>
              <ChakraUIProvider>
                {children}
              </ChakraUIProvider>
            </RecoilRoot>
          {/* </body> */}
        </Box>
      </Box>
    </html>
  );
}
